// locations.js

// Nigerian states and their local governments with locations - Comprehensive Version
// Major cities like Lagos, Abuja, Port Harcourt prioritized at top
const nigeriaLocations = {
  // MAJOR CITIES FIRST
  Lagos: {
    Ikeja: [
      "Ikeja GRA",
      "Allen Avenue",
      "Oregun",
      "Opebi",
      "Maryland",
      "Alausa",
      "Computer Village",
      "Anifowose",
      "Olowora",
      "Omole Phase 1",
      "Omole Phase 2",
      "Ogba",
      "Agidingbi",
      "Akiode",
      "Isheri",
    ],
    "Lagos Island": [
      "Lagos Island",
      "Ikoyi",
      "Victoria Island",
      "Obalende",
      "CMS",
      "Marina",
      "Onikan",
      "Dolphin Estate",
      "Osborne",
      "Banana Island",
    ],
    "Eti-Osa": [
      "Lekki Phase 1",
      "Lekki Phase 2",
      "Victoria Island",
      "Ikoyi",
      "Ajah",
      "Sangotedo",
      "Chevron",
      "Jakande",
      "Agungi",
      "Igbo Efon",
      "Ikate Elegushi",
      "Osapa London",
      "Chisco",
      "Ilasan",
      "Badore",
      "Abraham Adesanya",
      "Ogombo",
      "Awoyaya",
      "Lakowe",
    ],
    Alimosho: [
      "Ikotun",
      "Egbeda",
      "Iyana Ipaja",
      "Idimu",
      "Ayobo",
      "Ipaja",
      "Gowon Estate",
      "Akowonjo",
      "Shasha",
      "Isheri Olofin",
      "Igando",
      "Egan",
      "Obadore",
      "Governors Road",
      "Baruwa",
      "Abule Egba",
    ],
    Surulere: [
      "Surulere",
      "Aguda",
      "Ijeshatedo",
      "Ojuelegba",
      "Itire",
      "Lawanson",
      "Tejuosho",
      "Adeniran Ogunsanya",
      "Masha",
      "Stadium",
      "Bode Thomas",
      "Adelabu",
      "Empire",
      "Coker",
      "Orile",
    ],
    Kosofe: [
      "Ojota",
      "Ogudu",
      "Ketu",
      "Mile 12",
      "Magodo Phase 1",
      "Magodo Phase 2",
      "Isheri",
      "Alapere",
      "Ikosi",
      "Shangisha",
      "Mende",
      "Maryland",
      "Anthony Village",
      "Ifako",
      "Oworonshoki",
    ],
    Mushin: [
      "Mushin",
      "Idi-Araba",
      "Papa Ajao",
      "Ladipo",
      "Isolo",
      "Idi-Oro",
      "Ojuwoye",
      "Ilasamaja",
      "Alakara",
      "Babalosa",
    ],
    Ajeromi_Ifelodun: [
      "Ajegunle",
      "Amukoko",
      "Layeni",
      "Alaba Oro",
      "Awodi-Ora",
      "Mosafejo",
      "Wilmer",
      "Tolu",
      "Olodi",
      "Akpanu",
    ],
    Apapa: [
      "Apapa GRA",
      "Ajegunle",
      "Ijora",
      "Apapa Wharf",
      "Kirikiri",
      "Tin Can Island",
      "Olodi",
      "Aiyetoro",
      "Suru Alaba",
      "Trinity",
    ],
    Oshodi_Isolo: [
      "Oshodi",
      "Isolo",
      "Mafoluku",
      "Ejigbo",
      "Okota",
      "Ajao Estate",
      "Shogunle",
      "Bolade",
      "Matori",
      "Ilasamaja",
    ],
    Shomolu: [
      "Shomolu",
      "Bariga",
      "Gbagada",
      "Pedro",
      "Ifako",
      "Onipanu",
      "Palmgrove",
      "Oworonsoki",
      "Fadeyi",
      "Akoka",
    ],
    "Ifako-Ijaiye": [
      "Ifako",
      "Ijaiye",
      "Ogba",
      "Agege",
      "College Road",
      "Iju",
      "Ishaga",
      "Obawole",
      "Abule Egba",
      "Fagba",
    ],
    Amuwo_Odofin: [
      "Festac Town",
      "Amuwo",
      "Kirikiri",
      "Apple Junction",
      "Mile 2",
      "Satellite Town",
      "Abule Ado",
      "Trade Fair",
      "Durbar",
      "Ojo Barracks",
    ],
    Agege: [
      "Agege",
      "Dopemu",
      "Oko-Oba",
      "Papa Ashafa",
      "Orile Agege",
      "Isale Oja",
      "Pen Cinema",
      "Tabon Tabon",
      "Iloro",
      "Ogba",
    ],
    Ikorodu: [
      "Ikorodu Town",
      "Ijede",
      "Igbogbo",
      "Imota",
      "Bayeku",
      "Agbowa",
      "Gberigbe",
      "Isiu",
      "Ipakodo",
      "Agric",
      "Majidun",
      "Owutu",
      "Ibeshe",
      "Adamo",
      "Igbokuta",
    ],
    Badagry: [
      "Badagry Town",
      "Ajara",
      "Topo",
      "Aradagun",
      "Kankon",
      "Kweme",
      "Iworo",
      "Povita",
      "Iyafin",
      "Ganyingbo",
    ],
    Epe: [
      "Epe Town",
      "Mojoda",
      "Noforija",
      "Poka",
      "Eredo",
      "Ejirin",
      "Ibeju",
      "Lekki",
      "Eleko",
      "Akodo",
    ],
  },
  "Abuja FCT": {
    "Abuja Municipal": [
      "Garki",
      "Wuse",
      "Maitama",
      "Asokoro",
      "Gwarinpa",
      "Utako",
      "Central Business District",
      "Jabi",
      "Durumi",
      "Katampe",
      "Wuse Zone 1-7",
      "Gudu",
      "Life Camp",
      "Lokogoma",
      "Games Village",
      "Apo",
      "Gaduwa",
      "Galadimawa",
      "Dakibiyu",
      "Dei-Dei",
    ],
    Bwari: [
      "Bwari Town",
      "Kubwa",
      "Ushafa",
      "Dutse",
      "Mpape",
      "Gaba",
      "Jigo",
      "Byazhin",
      "Kuchiko",
      "Kawu",
    ],
    Gwagwalada: [
      "Gwagwalada Town",
      "Zuba",
      "Ibwa",
      "Dobi",
      "Paikon-Kore",
      "Tungan-Maje",
      "Anagada",
      "Kutunku",
      "Giri",
      "Dagiri",
    ],
    Kuje: [
      "Kuje Town",
      "Rubochi",
      "Gaube",
      "Pegi",
      "Chibiri",
      "Gwargwada",
      "Kabi",
      "Kwaita",
      "Chukuku",
      "Daddu",
    ],
    Abaji: [
      "Abaji Town",
      "Yaba",
      "Nuku",
      "Rimba",
      "Gurdi",
      "Gawu",
      "Naharati",
      "Moregi",
      "Sabon-Gari",
      "Kekeshi",
    ],
    Kwali: [
      "Kwali Town",
      "Yangoji",
      "Dafa",
      "Wako",
      "Pai",
      "Gumbo",
      "Kilankwa",
      "Sheda",
      "Ashara",
      "Gwaraji",
    ],
  },
  Rivers: {
    "Port Harcourt": [
      "Port Harcourt GRA",
      "D-Line",
      "Old GRA",
      "Rumuola",
      "Rumuokwuta",
      "Mile 1",
      "Mile 2",
      "Mile 3",
      "Mile 4",
      "Diobu",
      "Borokiri",
      "Amadi Flats",
      "New Layout",
      "Elelenwo",
      "Artillery",
      "Ogbunabali",
      "Orazi",
      "Marine Base",
      "Reclamation Road",
      "Eastern Bypass",
    ],
    "Obio/Akpor": [
      "Rumuigbo",
      "Rumuokoro",
      "Rumuodara",
      "Woji",
      "Rumuokwurusi",
      "Trans Amadi",
      "Eliozu",
      "Mgbuoba",
      "Eliowhani",
      "Eneka",
      "Rukpokwu",
      "Rumuomasi",
      "Rumukurushi",
      "Mgbuosimini",
      "Ozuoba",
      "Choba",
      "Rumuekini",
      "Alakahia",
      "Rumuodomaya",
      "Eligbolo",
    ],
    Eleme: [
      "Eleme",
      "Alesa",
      "Ebubu",
      "Eteo",
      "Onne",
      "Agbonchia",
      "Aleto",
      "Akpajo",
      "Ogale",
      "Ekporo",
    ],
    Oyigbo: [
      "Oyigbo Town",
      "Kom-kom",
      "Afam",
      "Obeakpu",
      "Umuagbai",
      "Mirinwayi",
      "Izuoma",
      "Okoloma",
      "Obete",
      "Obiohia",
    ],
  },

  // OTHER STATES ALPHABETICALLY
  Abia: {
    "Aba North": [
      "Ariaria",
      "Ogbor Hill",
      "Eziama",
      "Uratta",
      "Oko Nkwo",
      "Umuola",
      "Osusu",
      "Umuogor",
      "Egbelu",
      "Abayi"
    ],
    "Aba South": [
      "Aba Town",
      "Aba GRA",
      "Umungasi",
      "Ehere",
      "Ngwa Road",
      "Osisioma",
      "Abayi",
      "Ohabiam",
      "Ndiegoro",
      "Asa"
    ],
    "Umuahia North": [
      "Umuahia",
      "Ibeku",
      "Afara",
      "Ossah",
      "Amawom",
      "Ndume",
      "Amuzukwu",
      "Okwuta",
      "Umudike",
      "Isieke"
    ],
    "Umuahia South": [
      "Apumiri",
      "Olokoro",
      "Ubakala",
      "Nkwoegwu",
      "Umuopara",
      "Ehimiri",
      "Ohokobe",
      "Amakama",
      "Uzuakoli",
      "Ahiaeke"
    ],
  },
  Adamawa: {
    "Yola North": [
      "Jimeta",
      "Jambutu",
      "Karewa",
      "Luggere",
      "Alkalawa",
      "Doubeli",
      "Limawa",
      "Nasarawo",
      "Rumde",
      "Yelwa"
    ],
    "Yola South": [
      "Yola Town",
      "Mbamba",
      "Adarawo",
      "Ngurore",
      "Wuro Hausa",
      "Namtari",
      "Bole",
      "Njoboliyo",
      "Vunoklang",
      "Damare"
    ],
    Mubi: [
      "Mubi Town",
      "Sabon Layi",
      "Wuro Patuji",
      "Digil",
      "Lokuwa",
      "Kolomanga",
      "Kolere",
      "Wurobohari",
      "Chibluk",
      "Muchalla"
    ],
    Ganye: [
      "Ganye Town",
      "Gamu",
      "Gurum",
      "Jaggu",
      "Timdore",
      "Suwa",
      "Sabon Gari",
      "Sugu",
      "Wuro Bokki",
      "Yebbi"
    ],
  },
  "Akwa Ibom": {
    Uyo: [
      "Uyo Town",
      "Ewet Housing",
      "Shelter Afrique",
      "Ikot Ekpene Road",
      "Oron Road",
      "Nwaniba",
      "Etaha Itam",
      "Osongama Estate",
      "Ikpa Road",
      "Abak Road",
      "Mbiabong",
      "Use Offot",
      "Ifa",
      "Eket Road",
      "Udoudoma Avenue"
    ],
    "Ikot Ekpene": [
      "Ikot Ekpene Town",
      "Ikot Obong Edong",
      "Uruk Uso",
      "Ikot Ntuen",
      "Okop Eto",
      "Ukana",
      "Obot Akara",
      "Essien Udim",
      "Mbioto",
      "Abiakpo"
    ],
    Eket: [
      "Eket Town",
      "Okon",
      "Idua",
      "Afaha Eket",
      "Ikot Udoma",
      "Esit Urua",
      "Marina",
      "Afia Nsit",
      "Mkpok",
      "Atabong"
    ],
    Oron: [
      "Oron Town",
      "Udung Uko",
      "Urue Offong",
      "Oruko",
      "Okobo",
      "Mbo",
      "Enwang",
      "Ebughu",
      "Uda",
      "Eyoabasi"
    ],
  },
  Anambra: {
    "Awka South": [
      "Awka",
      "Amawbia",
      "Nibo",
      "Umuokpu",
      "Okpuno",
      "Isiagu",
      "Ezinato",
      "Agu-Awka",
      "Ifite-Awka",
      "Umudioka"
    ],
    "Onitsha North": [
      "Onitsha GRA",
      "Inland Town",
      "American Quarters",
      "Odoakpu",
      "Fegge",
      "Woliwo",
      "Trans-Nkisi",
      "Marine",
      "Uru",
      "Niger Bridge-Head"
    ],
    "Onitsha South": [
      "Fegge",
      "Woliwo",
      "Okpoko",
      "Aba Park",
      "Head Bridge",
      "Atani Road",
      "Harbor Industrial Layout",
      "Nkpor",
      "Obosi",
      "Iyiowa"
    ],
    "Nnewi North": [
      "Nnewi Central",
      "Umudim",
      "Otolo",
      "Uruagu",
      "Ave-Maria",
      "Okpunoeze",
      "Ichi",
      "Nnewichi",
      "Edoji",
      "Ukpor"
    ],
  },
  Bauchi: {
    Bauchi: [
      "Bauchi GRA",
      "Fadaman Mada",
      "Wunti",
      "Gudun",
      "Doya",
      "Makama",
      "Dutsen Tanshi",
      "Yelwa",
      "Dan Amar",
      "Ibrahim Bako"
    ],
    Azare: [
      "Azare Central",
      "Bakin Kura", 
      "Gadiya",
      "Katagum",
      "Bulkachuwa",
      "Jama'are",
      "Madara",
      "Chinade",
      "Sakwa",
      "Disina"
    ],
  },
  Bayelsa: {
    Yenagoa: [
      "Yenagoa Town",
      "Amarata",
      "Ovom",
      "Igbogene",
      "Biogbolo",
      "Kpansia",
      "Opolo",
      "Okutukutu",
      "Akenfa",
      "Edepie",
      "Ekeki",
      "Okaka",
      "Etegwe",
      "Yenizue Gene",
      "Tombia"
    ],
    Brass: [
      "Twon-Brass",
      "Okpoama",
      "Ewoama",
      "Diema",
      "Beletiama",
      "Egweama",
      "Liama",
      "Okumbiribeleu",
      "Sangana",
      "Obiata"
    ],
  },
  Benue: {
    Makurdi: [
      "Makurdi Town",
      "North Bank",
      "High Level",
      "Wurukum",
      "Wadata",
      "Modern Market",
      "Logo",
      "Old GRA",
      "New GRA",
      "Kanshio",
      "Apir",
      "Nyima",
      "Mission Ward",
      "Gyado Villa",
      "Fiidi"
    ],
    Gboko: [
      "Gboko Town",
      "Adekaa",
      "Mkar",
      "Yandev",
      "Bristow",
      "Gboko South",
      "Mbayion",
      "Mbakper",
      "Ameladu",
      "Genyi"
    ],
  },
  Borno: {
    Maiduguri: [
      "Maiduguri GRA",
      "Gwange",
      "Bulunkutu",
      "Gamboru",
      "Fori",
      "Gomari",
      "Bulabulin",
      "Mairi",
      "Old Maiduguri",
      "Pompomari",
      "Sabon Gari",
      "Shehuri North",
      "Shehuri South",
      "Monday Market",
      "Gwange"
    ],
    Bama: [
      "Bama Town",
      "Soye",
      "Gulumba",
      "Darajamal",
      "Banki",
      "Woloji",
      "Abbaram",
      "Kumshe",
      "Bama Central",
      "Kasugula"
    ],
  },
  "Cross River": {
    "Calabar Municipal": [
      "Calabar South",
      "Calabar GRA",
      "Big Qua",
      "State Housing",
      "Federal Housing",
      "Diamond Hill",
      "Ikot Ishie",
      "Ediba Road",
      "Target",
      "Ekpo Abasi",
      "Edim Otop",
      "Ikot Ansa",
      "Satellite Town",
      "Akim",
      "Parliamentary"
    ],
    "Calabar South": [
      "Anantigha",
      "Ekeng Ewa",
      "Etta Agbor",
      "Mbukpa",
      "Mount Zion",
      "Uwanse",
      "Diamond",
      "Goldie",
      "White House",
      "Ekpo Abasi"
    ],
    Ikom: [
      "Ikom Urban",
      "Akparabong",
      "Ajassor",
      "Nkum",
      "Nta-Nselle",
      "Ofutop",
      "Olulumo",
      "Ikom Central",
      "Abinti",
      "Okuni"
    ],
  },
  Delta: {
    "Warri South": [
      "Warri GRA",
      "Okumagba Layout",
      "Airport Road",
      "Ubeji",
      "Igbudu",
      "Enerhen",
      "Jakpa",
      "Ekurede",
      "Deco Road",
      "Ugborikoko",
      "Odion",
      "Okere",
      "Ajamimogha",
      "Alders Town",
      "Ogunu"
    ],
    Asaba: [
      "Asaba GRA",
      "Okwe",
      "Cable Point",
      "Ibusa Road",
      "Nnebisi Road",
      "Anwai Road",
      "West End",
      "Core Area",
      "Summit Road",
      "Okpanam Road",
      "DLA Road",
      "Isieke",
      "Ezenei Avenue",
      "Jesus Saves",
      "Umuagu"
    ],
    "Uvwie (Effurun)": [
      "Effurun GRA",
      "PTI Road",
      "Alegbo",
      "DSC Township",
      "Ekpan",
      "Ebrumede",
      "Ugboroke",
      "Ugbomro",
      "Okuokoko",
      "Osubi"
    ],
    Sapele: [
      "Sapele GRA",
      "Amukpe",
      "Okirighwre",
      "Shell Road",
      "New Road",
      "Mission Road",
      "Ajogodo",
      "Ugbeyiyi",
      "Uruakpa",
      "Aladja"
    ],
  },
  Ebonyi: {
    Abakaliki: [
      "Abakaliki Town",
      "Kpirikpiri",
      "Abakpa",
      "Azuiyiokwu",
      "Ntezi",
      "Amagu",
      "Onueke",
      "Ezza South",
      "Nkaliki",
      "Presco",
      "Ishieke",
      "Udemezue",
      "Achara",
      "Amike-Aba",
      "Ngodo"
    ],
    Afikpo: [
      "Afikpo Town",
      "Unwana",
      "Ozizza",
      "Amasiri",
      "Nkpoghoro",
      "Itim",
      "Akpoha",
      "Ugwuegu",
      "Enohia",
      "Owutu"
    ],
  },
  Edo: {
    "Benin City": [
      "GRA",
      "Ugbowo",
      "Aduwawa",
      "Sapele Road",
      "Airport Road",
      "Okhoro",
      "New Benin",
      "Ikpoba Hill",
      "Uselu",
      "Ring Road",
      "Oregbeni",
      "Egor",
      "Ogida",
      "Okhoro",
      "Evbuotubu",
      "Uwasota",
      "Upper Sakponba",
      "Textile Mill Road",
      "Ogbe",
      "Ibiwe"
    ],
    Auchi: [
      "Auchi Town",
      "Jattu",
      "Aviele",
      "Uzairue",
      "Ayua",
      "South Ibie",
      "Afashio",
      "Ivhiunone",
      "Iyora",
      "Iyekhei"
    ],
    Ekpoma: [
      "Ekpoma Town",
      "Emaudo",
      "Iruekpen",
      "Illeh",
      "Eguare",
      "Ujemen",
      "Idoa",
      "Ikhideu",
      "Uke",
      "Uhiele"
    ],
  },
  Ekiti: {
    "Ado Ekiti": [
      "Ado Ekiti GRA",
      "Ajilosun",
      "Basiri",
      "Adebayo",
      "Iworoko Road",
      "Dalimore",
      "Oke-Ila",
      "Okesa",
      "Oke-Isha",
      "Irona",
      "Odo Ado",
      "Ijigbo",
      "Oke-Iyinmi",
      "Falegan",
      "Mojere"
    ],
    Ikere: [
      "Ikere Town",
      "Okeruku",
      "Afao Road",
      "Odo-Oja",
      "Oke-Osun",
      "Ijo-Mimo",
      "Ogbonjana",
      "Amoye",
      "Araromi",
      "Ilapetu"
    ],
    Ikole: [
      "Ikole Town",
      "Oye",
      "Iropora",
      "Ijesha-Isu",
      "Ikun",
      "Iyemero",
      "Ipao",
      "Itapaji",
      "Ayebode",
      "Odo-Ayedun"
    ],
  },
  Enugu: {
    "Enugu North": [
      "Enugu GRA",
      "New Haven",
      "Independence Layout",
      "Ogui",
      "Coal Camp",
      "Asata",
      "Ogbete",
      "Iva Valley",
      "Ogui New Layout",
      "Trans Ekulu",
      "Nike Lake Road",
      "Artisan",
      "Ngwo",
      "New Layout",
      "Obiagu"
    ],
    "Enugu South": [
      "Achara Layout",
      "Uwani",
      "Maryland",
      "Awkunanaw",
      "Ugwuaji",
      "Idaw River",
      "Gariki",
      "Agbani Road",
      "Akwuke",
      "Premier Layout",
      "Amechi",
      "Heritage Estate",
      "Obeagu",
      "Topland",
      "Goshen"
    ],
    Nsukka: [
      "Nsukka Town",
      "University of Nigeria Nsukka",
      "Orba Road",
      "Odenigbo",
      "Odim",
      "Onuiyi",
      "Ajuona",
      "Obukpa",
      "Ikpuiga",
      "Ede-Oballa"
    ],
  },
  Gombe: {
    Gombe: [
      "Gombe GRA",
      "Federal Low-cost",
      "Checheniya",
      "Pantami",
      "Bolari",
      "Herwagana",
      "Bagadaza",
      "Jankai",
      "Dawaki",
      "Tudun Wada",
      "Nassarawo",
      "Yelenguruza",
      "Barunde",
      "Kumbia-Kumbia",
      "New Mile 3"
    ],
    Billiri: [
      "Billiri Town",
      "Bare",
      "Tal",
      "Tangaltong",
      "Banganje",
      "Kombani",
      "Kalmai",
      "Pandin",
      "Tudu",
      "Lapandi"
    ],
  },
  Imo: {
    "Owerri Municipal": [
      "Owerri GRA",
      "Ikenegbu",
      "Aladinma",
      "New Owerri",
      "World Bank Housing Estate",
      "Prefab",
      "Trans Egbu",
      "Amakohia",
      "Orji",
      "Uratta",
      "Irete",
      "Egbeada",
      "Works Layout",
      "Federal Housing",
      "Umuguma"
    ],
  },
  Jigawa: {
    Dutse: ["Dutse GRA", "Takur Site", "Fagoji", "Danmasara", "Yalwawa", "Zai"],
    Hadejia: ["Hadejia GRA", "Gagulmari", "Kasuwar Kofa", "Matsaro", "Zareku"],
    Gumel: ["Gumel GRA", "Garin Gabas", "Garin Yamma", "Kogin Garu", "Hammado"],
    Ringim: ["Ringim Central", "Yandaka", "Daushe", "Yakasai", "Chai-Chai"],
  },
  
  Kaduna: {
    "Kaduna North": ["Kaduna GRA", "Unguwan Rimi", "Malali", "Kabala Costain", "Unguwan Sarki", "Badiko"],
    "Kaduna South": ["Barnawa", "Television", "Sabon Tasha", "Narayi", "Gonin Gora", "Ungwan Sunday"],
    Zaria: ["Zaria City", "Samaru", "Sabon Gari", "Wusasa", "Kongo", "Tudun Wada"],
    Kafanchan: ["Kafanchan GRA", "Ungwan Masara", "Ungwan Fari", "Katsit", "Zipak", "Garaje"]
  },
  
  Kano: {
    "Kano Municipal": ["Kano GRA", "Nasarawa", "Fagge", "Sabon Gari", "Kurna", "Sharada"],
    "Kano Fagge": ["Fagge GRA", "Sabongari", "Rijiyar Lemo", "Court Road", "Brigade"],
    "Kano Dala": ["Bakin Ruwa", "Kabuwaya", "Gobirawa", "Unguwar Gini", "Dala"],
    "Kano Gwale": ["Gwale", "Dorayi", "Kofar Mazugal", "Kabuga", "Galadanci"]
  },
  
  Katsina: {
    Katsina: ["Katsina GRA", "Kofar Kaura", "Kofar Kwaya", "Layout", "Kofar Durbi", "Kofar Marusa"],
    Daura: ["Daura GRA", "Kalgo", "Kusugu", "Sabon Sara", "Kofar Arewa", "Zango"],
    Funtua: ["Funtua GRA", "Makera", "Tudun Wada", "Sabuwar Unguwa", "Low-cost", "Unguwar Ibrahim"],
    Jibia: ["Jibia Central", "Mazanya", "Ungwar Malamai", "Ungwar Dole", "Kaura"]
  },
  
  Kebbi: {
    "Birnin Kebbi": ["Birnin Kebbi GRA", "Badariya", "Nassarawa", "Tudun Wada", "Gesse", "Rafin Atiku"],
    Argungu: ["Argungu GRA", "Zoramawa", "Kokani", "Kashin Zama", "Gazari", "Filin Jirgi"],
    Yauri: ["Yauri GRA", "Tondi", "Yelwa", "Jijima", "Nasarawa", "Kyauru"],
    Zuru: ["Zuru GRA", "Dabai", "Senchi", "Bedi", "Manga", "Rikoto"]
  },
  
  Kogi: {
    Lokoja: ["Lokoja GRA", "Adankolo", "Felele", "Ganaja", "Phase 1", "Phase 2"],
    Okene: ["Okene GRA", "Agassa", "Idoji", "Bariki", "Ikuehi", "Ori-Apata"],
    Kabba: ["Kabba GRA", "Asuta", "Odolu", "Okenyi", "Ayetoro-Gbede", "Inoziomi"],
    Idah: ["Idah GRA", "Ukwaja", "Ega", "Sabon Gari", "Igalogba", "Angwa"]
  },
  
  Kwara: {
    Ilorin: ["Ilorin GRA", "Adewole", "Tanke", "Gaa Akanbi", "Oloje", "Fate"],
    Offa: ["Offa GRA", "Igbonna", "Balogun", "Shawo", "Popo", "Olorin"],
    Lafiagi: ["Lafiagi Central", "Gbugbu", "Chikanda", "Tsonga", "Buhari", "Emma"],
    Patigi: ["Patigi GRA", "Kpada", "Lade", "Sakpefu", "Rogun", "Dzwaegi"]
  },
  
  Nasarawa: {
    Lafia: ["Lafia GRA", "Millionaires Quarters", "Bukan Sidi", "Tudun Gwandara", "Ombi 1", "Ombi 2"],
    Keffi: ["Keffi GRA", "Angwan Rimi", "Tsohon Tasha", "Sabon Gari", "Angwan Waje", "Masaka"],
    Akwanga: ["Akwanga GRA", "Gudi", "Andaha", "Ningo", "Gwanje", "Moro"],
    Nasarawa: ["Nasarawa GRA", "Tammah", "Laminga", "Udenin Gida", "Loko", "Udege"]
  },
  
  Niger: {
    Minna: ["Minna GRA", "Tunga", "Bosso", "Maitumbi", "Kpakungu", "Chanchaga"],
    Bida: ["Bida GRA", "Dokodza", "Masaga", "Wadata", "Mayaki", "Kyari"],
    Suleja: ["Suleja GRA", "Bagama", "Kurmin Sarki", "Hashimi", "Rafin Sanyi", "Madalla"],
    Kontagora: ["Kontagora GRA", "Tunga Kawo", "Unguwar Yamma", "Masama", "Tunga Giwa", "Maduwari"]
  },
  
  Ogun: {
    "Abeokuta South": ["Abeokuta GRA", "Ibara", "Oke Ilewo", "Kuto", "Isale Igbein", "Itoko"],
    "Ado-Odo/Ota": ["Ota", "Sango", "Ijoko", "Iju", "Ilogbo", "Atan"],
    "Ijebu-Ode": ["Ijebu-Ode GRA", "Folagbade", "Oke-Aje", "Italapo", "Igbeba", "Mobalufon"],
    Sagamu: ["Sagamu GRA", "Sabo", "Makun", "Ijagba", "Ode-Lemo", "Sotubo"]
  },
  
  Ondo: {
    "Akure South": ["Akure GRA", "Alagbaka", "Oba Ile", "Ijapo", "Oke Aro", "Fanibi"],
    Ondo: ["Ondo GRA", "Surulere", "Fagun", "Yaba", "Valentino", "Mobil"],
    Owo: ["Owo GRA", "Ijebu", "Iselu", "Imola", "Ehinogbe", "Idashen"],
    Ilaje: ["Igbokoda", "Mahin", "Ugbo", "Ayetoro", "Zion Pepe", "Orioke"]
  },
  
  Osun: {
    Osogbo: ["Osogbo GRA", "Alekuwodo", "Okefia", "Oke Baale", "Oja Oba", "Isale Osun"],
    "Ile-Ife": ["Ife GRA", "Lagere", "Mayfair", "Eleyele", "Modakeke", "Parakin"],
    Ilesa: ["Ilesa GRA", "Okesa", "Imo", "Ijoka", "Iroye", "Ibala"],
    Ede: ["Ede GRA", "Timi", "Alusekere", "Papa", "Agip", "Akoda"]
  },
  
  Oyo: {
    "Ibadan North": ["Bodija", "Agodi GRA", "Ikolaba", "Sango", "Bashorun", "Mokola"],
    "Ibadan South-West": ["Ring Road", "Challenge", "Oluyole", "Oke Ado", "Apata", "Alesinloye"],
    Ogbomosho: ["Ogbomosho GRA", "Arowomole", "Oke Alapata", "Isale Ora", "Takie", "Caretaker"],
    Oyo: ["Oyo GRA", "Akeetan", "Isale Oyo", "Awe", "Ilora", "Erelu"]
  },
  
  Plateau: {
    "Jos North": ["Jos GRA", "Terminus", "Apata", "Jenta", "Laranto", "Tafawa Balewa"],
    "Jos South": ["Bukuru", "Rayfield", "Kuru", "Vom", "Zawan", "Gyel"],
    Pankshin: ["Pankshin GRA", "Wokkos", "Chip", "Lankaku", "Dyis", "Kangshu"],
    Shendam: ["Shendam GRA", "Yelwa", "Dokan Tofa", "Pangshak", "Demshin", "Dorok"]
  },
  
  Rivers: {
    "Port Harcourt": ["Port Harcourt GRA", "D-Line", "Old GRA", "Rumuola", "Rumuokwuta", "Diobu"],
    "Obio/Akpor": ["Rumuigbo", "Rumuokoro", "Rumuodara", "Woji", "Rumuokwurusi", "Elelenwo"],
    Eleme: ["Eleme GRA", "Akpajo", "Aleto", "Agbonchia", "Ogale", "Onne"],
    Bonny: ["Bonny GRA", "Finima", "Abalamabie", "Iwoma", "Akiama", "Orosikiri"]
  },
  
  Sokoto: {
    "Sokoto North": ["Sokoto GRA", "Gawon Nama", "Arkilla", "Runjin Sambo", "Marina", "Kofar Atiku"],
    "Sokoto South": ["Tudun Wada", "Old Airport", "Mabera", "Gagi", "Dundaye", "Kwanni"],
    Tambuwal: ["Tambuwal GRA", "Dogon Daji", "Sanyinna", "Kaffe", "Bakaya", "Jabo"],
    Illela: ["Illela GRA", "Gada", "Damba", "Kalmalo", "Kware", "Gwadabawa"]
  },
  
  Taraba: {
    Jalingo: ["Jalingo GRA", "Sabon Gari", "Kona", "Mayo Gwoi", "Kofai", "Magami"],
    Wukari: ["Wukari GRA", "Puje", "Avyi", "Tsokundi", "Hospital Area", "Rafin Kada"],
    Zing: ["Zing GRA", "Monkin", "Yakoko", "Bitako", "Dadin Kowa", "Lamma"],
    Bali: ["Bali GRA", "Gangdole", "Sabon Layi", "Teli", "Gazabu", "Sabongida"]
  },
  
  Yobe: {
    Damaturu: ["Damaturu GRA", "Nayi Nawa", "Pawari", "Abasha", "Gwange", "Nyanya"],
    Potiskum: ["Potiskum GRA", "Arikime", "Doya", "Hausari", "Bolewa", "Mamudo"],
    Gashua: ["Gashua GRA", "Zango", "Lawan Fannami", "Lawan Musa", "Sabon Gari", "Zango"],
    Geidam: ["Geidam GRA", "Ashekri", "Kawuri", "Fulatari", "Dumburi", "Kelluri"]
  },
  
  Zamfara: {
    Gusau: ["Gusau GRA", "Tudun Wada", "Sabon Gari", "Samaru", "Unguwar Dallatu", "Zawiyya"],
    "Kaura Namoda": ["Kaura Namoda GRA", "Sabon Gari", "Kurya", "Nasarawa", "Maguru", "Yankaba"],
    "Talata Mafara": ["Talata Mafara GRA", "Bakin Kasuwa", "Sabon Gari", "Mayanchi", "Ruwan Bore", "Garbadu"],
    Anka: ["Anka GRA", "Bagega", "Sabon Gari", "Wuya", "Yar-Galma", "Barayar Zaki"]
  },
};

export default nigeriaLocations;